# Generated by Django 3.2.5 on 2021-07-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_prod', models.IntegerField(default=0)),
                ('player_one_vp', models.IntegerField(default=0)),
                ('player_one_dc', models.IntegerField(default=0)),
                ('player_one_stolen', models.IntegerField(default=0)),
                ('player_two_prod', models.IntegerField(default=0)),
                ('player_two_vp', models.IntegerField(default=0)),
                ('player_two_dc', models.IntegerField(default=0)),
                ('player_two_stolen', models.IntegerField(default=0)),
                ('player_three_prod', models.IntegerField(blank=True, null=True)),
                ('player_three_vp', models.IntegerField(blank=True, null=True)),
                ('player_three_dc', models.IntegerField(blank=True, null=True)),
                ('player_three_stolen', models.IntegerField(blank=True, null=True)),
                ('player_four_prod', models.IntegerField(blank=True, null=True)),
                ('player_four_vp', models.IntegerField(blank=True, null=True)),
                ('player_four_dc', models.IntegerField(blank=True, null=True)),
                ('player_four_stolen', models.IntegerField(blank=True, null=True)),
                ('twos', models.IntegerField(default=0)),
                ('threes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('fives', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('sevens', models.IntegerField(default=0)),
                ('eights', models.IntegerField(default=0)),
                ('nines', models.IntegerField(default=0)),
                ('tens', models.IntegerField(default=0)),
                ('elevens', models.IntegerField(default=0)),
                ('twelves', models.IntegerField(default=0)),
                ('variant', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('largest_army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='largest_army', to='stats.player')),
                ('longest_road', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longest_road', to='stats.player')),
                ('player_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_four', to='stats.player')),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one', to='stats.player')),
                ('player_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_three', to='stats.player')),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two', to='stats.player')),
            ],
        ),
    ]
